# Generated by Django 2.2.5 on 2019-09-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wearings',
            new_name='Electronic',
        ),
        migrations.RenameModel(
            old_name='Electronics',
            new_name='Fruit',
        ),
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Wearing',
        ),
    ]
