# Generated by Django 2.2.5 on 2019-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190914_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wearing',
        ),
        migrations.AlterField(
            model_name='electronic',
            name='image',
            field=models.ImageField(default='electronic.jpg', upload_to='electronic'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(default='fruit.jpg', upload_to='fruit'),
        ),
    ]
