# Generated by Django 2.2.5 on 2020-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200915_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='products.Article'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
